# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
  - 2.10.1
  - 2.10.2
  - 2.10.3
  
script: sbt clean scalastyle test

# Testing with OpenJDK7 as well just to be adventurous!
jdk:
  - oraclejdk7
  - openjdk7

# Custom notification settings
notifications:
  email:
    recipients:
      - anirvanchakraborty@gmail.com
      - jan.machacek@gmail.com